---
-
  name: Creates digger-jenkins repo folder directory
  file:
    path: "{{ digger_jenkins_folder }}"
    state: directory
-
  name: Checkout digger-jenkins branch
  git:
    repo: "{{ digger_jenkins_repo }}"
    dest: "{{ digger_jenkins_folder }}"
    version: "{{ digger_jenkins_head }}"
