#!/bin/bash

DIR=$(dirname "$(readlink -f "$0")")

getopts ":y" _ANSWER

if [ "$_ANSWER" != "?" ]; then
  ANSWER='y'
  shift
fi

if [ -z "$ANSWER" ]; then
  ANSWER='n'
fi

CMD="python $DIR/androidctl $@"

expect -c "
set timeout -1;
spawn $CMD
expect {
    \"Accept? (y/N):\" { 
      exp_send \"$ANSWER\r\";
      if {$ANSWER eq \"y\"} {
        exp_send \"Android SDK license accepted, resuming installation process...\n\";
      }
      exp_continue;
    }
    eof
}
"
