FROM openshift/jenkins-2-rhel7

COPY ./contrib/kube-slave-common.sh /usr/local/bin/kube-slave-common.sh

COPY plugins.txt /opt/openshift/configuration/plugins.txt
RUN /usr/local/bin/install-plugins.sh /opt/openshift/configuration/plugins.txt && \
    mkdir $JENKINS_HOME/secrets && \
    echo "false" > $JENKINS_HOME/secrets/slave-to-master-security-kill-switch && \
    ## Prevent admins from changing master to slave security option
    chmod 444 $JENKINS_HOME/secrets/slave-to-master-security-kill-switch
