apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "android-sdk-pv1"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  glusterfs:
    endpoints: "gluster"
    path: "android-sdk"
    readOnly: false
  persistentVolumeReclaimPolicy: "Retain"
